### ISSUE TITLE
`neat-interpolation` Quasiquoter fails when using `where`-clause

### ISSUE THREAD

**Issue by Profpatsch** [ghcjs/ghcjs#617]
This minimal example:

`QQBug.hs`
```haskell
{-# LANGUAGE OverloadedStrings  #-}
{-# LANGUAGE QuasiQuotes        #-}
module QQBug (
      test
    ) where

import qualified NeatInterpolation
import Data.Text

-- txt = "test1"

test :: Text
test = [NeatInterpolation.text|$txt|]
    where
      txt = "test"
```

causes TemplateHaskell to fail with ghcjs:

```
 2017-11-25 00:54:47 ☆  katara in ~/code/haskell/dhall-json
○ → ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.1 (GHC 8.0.2)

 2017-11-25 01:02:07 ☆  katara in ~/code/haskell/dhall-json
○ → ghcjs QQBug.hs
[1 of 1] Compiling QQBug            ( QQBug.hs, QQBug.js_o )
runNodeInteractive
Linking Template Haskell (ThRunner1)

QQBug.hs:13:8: error:
    • The exact Name ‘txt_XN’ is not in scope
        Probable cause: you used a unique Template Haskell name (NameU), 
        perhaps via newName, but did not bind it
        If that's it, then -ddump-splices might be useful
    • In the quasi-quotation: [NeatInterpolation.text|$txt|]
```

If I use the commented-out version of `txt` instead of the where clause, it works just fine:

```
 2017-11-25 01:03:06 ☆  katara in ~/code/haskell/dhall-json
○ → ghcjs QQBug.hs
[1 of 1] Compiling QQBug            ( QQBug.hs, QQBug.js_o )
runNodeInteractive
Linking Template Haskell (ThRunner1)
```

All this was done on current nixpkgs master (`32169472017ac91e763cc7ff97f232c99d4db663`), with the nix invocation: `nix-build -A haskell.packages.ghjcsHEAD.dhall-json ./nixpkgs`

It works with GHC `8.0.2` and `8.2.2` .

The following nix expression can set up an environment to test the example with various versions of GHC:

`shell.nix`
```nix
{ ghcVersion }:
((import <nixpkgs> {}).haskell.packages."${ghcVersion}".override {
  overrides = self: super: {
    my-pkg = super.mkDerivation {
      pname = "pkg-env";
      src = "/dev/null";
      version = "none";
      license = "none";
      buildDepends = [ self.neat-interpolation ];
    };
  };
}).my-pkg.env
```

8.0.2: `nix-shell -I nixpkgs=/path/to/nixpkgs ./shell.nix --argstr ghcVersion ghc802`
8.2.2: `nix-shell -I nixpkgs=/path/to/nixpkgs ./shell.nix --argstr ghcVersion ghc802`
ghcjs 8.0.2: `nix-shell -I nixpkgs=/path/to/nixpkgs ./shell.nix --argstr ghcVersion ghcHEAD`

This issue came up while trying to build `dhall-json`: https://github.com/dhall-lang/dhall-json/issues/12

**Comment by luite** [comment]
64 bit? If you have the possibility to test: Does this also happen with 32
bit GHC?

**Comment by Profpatsch** [comment]
32-bit GHC `8.0.2`:

```
 2017-11-25 02:07:33 ☆  katara in ~/code/haskell/dhall-json
○ → cat $(type -p ghc)
#! /nix/store/gxqck2wch5mglvzj4lg0r66m1skyf2i8-bash-4.4-p12/bin/bash -e
export NIX_GHC="/nix/store/wxwy2myn8zi8541530a2n30wm0r698ih-ghc-8.0.2-with-packages/bin/ghc"
export NIX_GHCPKG="/nix/store/wxwy2myn8zi8541530a2n30wm0r698ih-ghc-8.0.2-with-packages/bin/ghc-pkg"
export NIX_GHC_DOCDIR="/nix/store/wxwy2myn8zi8541530a2n30wm0r698ih-ghc-8.0.2-with-packages/share/doc/ghc/html"
export NIX_GHC_LIBDIR="/nix/store/wxwy2myn8zi8541530a2n30wm0r698ih-ghc-8.0.2-with-packages/lib/ghc-8.0.2"
exec "/nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/bin/ghc"  "-B$NIX_GHC_LIBDIR" "${extraFlagsArray[@]}" "$@"

 2017-11-25 02:07:36 ☆  katara in ~/code/haskell/dhall-json
○ → cat /nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/bin/ghc
#!/nix/store/gxqck2wch5mglvzj4lg0r66m1skyf2i8-bash-4.4-p12/bin/bash
export PATH="$PATH:/nix/store/zs082c6wsbb5jbm935kij9zs48d0bc7k-binutils-2.28.1/bin:/nix/store/99wk4vdfr4x9pyxvfrk8zb0l2alc68jq-coreutils-8.28/bin"
exedir="/nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/lib/ghc-8.0.2/bin"
exeprog="ghc-stage2"
executablename="$exedir/$exeprog"
datadir="oc/share/doc/ghc"
bindir="/nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/bin"
topdir="/nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/lib/ghc-8.0.2"
executablename="$exedir/ghc"
exec "$executablename" -B"$topdir" ${1+"$@"}

 2017-11-25 02:07:53 ☆  katara in ~/code/haskell/dhall-json
○ → file /nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/lib/ghc-8.0.2/bin/ghc
/nix/store/lbyiybcidisf679lp6wjjl2hqwlknmcp-ghc-8.0.2/lib/ghc-8.0.2/bin/ghc: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /nix/store/c8gawxwqff2q7yp4f4ly79halyp06pxk-glibc-2.26-75/lib/ld-linux.so.2, for GNU/Linux 3.2.0, not stripped

 2017-11-25 02:09:15 ☆  katara in ~/code/haskell/dhall-json
○ → ghc QQBug.hs
[1 of 1] Compiling QQBug            ( QQBug.hs, QQBug.o )
```

32-bit GHCJS is still compiling, that might take a while …

Invocation:
changed the second line of `shell.nix` above to
`((import <nixpkgs> { system = "i686-linux"; }).haskell.packages."${ghcVersion}".override {
`

**Comment by Profpatsch** [comment]
YES, it works with the 32-bit GHCJS executable. oO

```
 2017-11-25 22:28:35 ☆  katara in ~/code/haskell/dhall-json
○ → type -p ghcjs
/nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/bin/ghcjs

 2017-11-25 22:28:41 ☆  katara in ~/code/haskell/dhall-json
○ → cat /nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/bin/ghcjs
#! /nix/store/gxqck2wch5mglvzj4lg0r66m1skyf2i8-bash-4.4-p12/bin/bash -e
export NIX_GHCJS="/nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/bin/ghcjs"
export NIX_GHCJSPKG="/nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/bin/ghcjs-pkg"
export NIX_GHCJS_DOCDIR="/nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/share/doc/ghc/html"
export NIX_GHCJS_LIBDIR="/nix/store/m08w1gn2f91h588zsq97qialdzsx8m0f-ghcjs-0.2.020170323-with-packages/lib/ghcjs-0.2.020170323"
export NODE_PATH="/nix/store/il8xwmx7hjrbvicxcv8v7x4b96nzr19d-node-socket.io-2.0.4/lib/node_modules"
exec "/nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/bin/ghcjs"  "-B$NIX_GHCJS_LIBDIR" "${extraFlagsArray[@]}" "$@"

 2017-11-25 22:28:43 ☆  katara in ~/code/haskell/dhall-json
○ → cat /nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/bin/ghcjs
#!/nix/store/gxqck2wch5mglvzj4lg0r66m1skyf2i8-bash-4.4-p12/bin/sh

# wrapper script to pass the correct -B option to ghcjs.bin
# ghcjs-boot does substitution of {...} sections

topdir="/nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/lib/ghcjs-0.2.020170323"
executablename="/nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/bin/ghcjs-0.2.1-8.0.2.bin"
exec "$executablename" -B"$topdir" ${1+"$@"}

 2017-11-25 22:28:47 ☆  katara in ~/code/haskell/dhall-json
○ → file /nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/bin/ghcjs-0.2.1-8.0.2.bin
/nix/store/hy6hjngyaizzgznllh6hsqzpyc4nfb28-ghcjs-0.2.020170323/bin/ghcjs-0.2.1-8.0.2.bin: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /nix/store/c8gawxwqff2q7yp4f4ly79halyp06pxk-glibc-2.26-75/lib/ld-linux.so.2, for GNU/Linux 3.2.0, stripped

 2017-11-25 22:28:50 ☆  katara in ~/code/haskell/dhall-json
○ → rm QQBug.{dyn_*,js*,hi,o}
rm: cannot remove 'QQBug.dyn_*': No such file or directory
rm: cannot remove 'QQBug.hi': No such file or directory
rm: cannot remove 'QQBug.o': No such file or directory

 2017-11-25 22:28:59 ☆  katara in ~/code/haskell/dhall-json
○ → ghcjs QQBug.hs 
[1 of 1] Compiling QQBug            ( QQBug.hs, QQBug.js_o )
runNodeInteractive
Linking Template Haskell (ThRunner1)
```

**Comment by luite** [comment]
So my theory is that the `Unique` in the TH name is truncated, since it's
an `Int`. GHCJS on a 64 bit host has 64 bit uniques, but in JavaScript the
`Int` is 32 bit. So it doesn't survive the roundtrip.

This is a bigger problem with 8.2 for some reason. I'm not yet sure what
the fix should be. I'm thinking of making the `Unique` field `Int64` or
`Integer` but that requires changes ton`DsMeta` in GHC

**Comment by Profpatsch** [comment]
> GHCJS on a 64 bit host has 64 bit uniques, but in JavaScript the
> `Int` is 32 bit. So it doesn't survive the roundtrip.

Can we pass the 64 bits as two JS 32bit integers then?

**Comment by luite** [comment]
We can change the field to `Int64` in the `template-haskell` library so that the platform that runs the Template Haskell always enough space to represent the whole unique. GHCJS compiles that to two JS ints.

Unfortunately I haven't found a workaround to make it work with an existing `ghc` library because of the required change in `DsMeta`. I'm now working on building against a modified `ghc` library installable as a Cabal package. Perhaps that will be the way GHCJS on 8.2 has to be built.

hvr's upload of the `ghc` library on hackage ( http://hackage.haskell.org/package/ghc ) was my starting point. I've been building against a modified version of that for a few days now.

**Comment by luite** [comment]
I have a fix that changes the field in the `template-haskell` library to `Integer` and a patch for GHC 8.4/master. That solves the problem.

Unfortunately this breakage seems to affect much more TH code on 8.2 than on 8.0, making Template Haskell almost unusable, if we released GHCJS on 8.2 the old way.

I now have GHCJS with properly working Template Haskell on 8.2, with a customized GHC library. This also requires a few other packages to be "forked":

 * `ghc-api-ghcjs` (fork of `ghc`, desugaring changes for Template Haskell)
 * `template-haskell-ghcjs` (fork of `template-haskell`)
 * `ghci-ghcjs` (fork of `ghci`, updated to depend on `ghc-api-ghcjs`)
 * `haddock-api-ghcjs` (fork of `haddock-api`, updated to depend on `ghc-api-ghcjs`)

The good news is that going forward, it is much easier to make changes in the GHC tree usable for GHCJS.

**Comment by luite** [comment]
also see: https://ghc.haskell.org/trac/ghc/ticket/14574

**Comment by cliffordbeshers** [comment]
Does 'working properly' in this case mean not using nodejs to do the work?

**Comment by luite** [comment]
it still uses node.js, but it doesn't truncate `Uniq` identifiers to 32 bits anymore.

earlier this year a performance bug with TH on large programs was fixed (quadratic performance blowup because of buffer handling) 

even after that fix, Template Haskell will still be slower than with native GHC, but it should be usable in most situations. If you have a good test case for a performance or memory consumption problem, please open a ticket.

**Comment by 3noch** [comment]
AFAIK, using nodejs is all but necessary because TH splices could call out to FFI, which in GHCJS would be JS.

**Comment by luite** [comment]
this works correctly with the `ghc-8.2` branch on my system.

unfortunately I don't know a way to easily fix it for `ghc-8.0`, since this is mainly an upstream problem.

**Comment by Profpatsch** [comment]
> this works correctly with the ghc-8.2 branch on my system.

You mean the fix is upstream now in 8.2?

**Comment by 3noch** [comment]
I think he means the `ghc-8.2` branch in this repo.

**Comment by luite** [comment]
yup I meant this repo.

the fix is in a fork of the ghc repo (also under the ghcjs organization on github).

ghcjs builds against its own "private" GHC library based on those sources. The package is called `ghc-api-ghcjs` and it's really the upstream sources (from a submodule with this bugfix) made buildable as a cabal package. See the `/utils/makePackages.sh` and `/utils/makeSandbox.sh` for how to set up a build environment.

**Comment by luite** [comment]
fixed in the `ghc-8.2` branch, which should be usable by now. a backport would be tricky.

please open a new ticket if you really nead one or have ideas on how to do it.
