### ISSUE TITLE
ghc-8.0 branch failed to build with ghc-8.0.1 (lts-7.9)

### ISSUE THREAD

**Issue by sighingnow** [ghcjs/ghcjs#593]
Currently, the ghc-8.0 branch failed to build with ghc-8.0.1 (lts-7.9), both the latest code in ghc-8.0 branch or the nightly snapshot (ghc-8.0-20170616.tar.gz) downloaded from http://ghcjs.luite.com/.

The error message:

~~~
ghcjs-0.2.1\src\Gen2\Linker.hs:354:42: error:
    * Couldn't match type `[Char]' with `ByteString'
      Expected type: ByteString
        Actual type: FilePath
    * In the first argument of `bsLit', namely
        `(nodeProgram nodeSettings)'
      In the expression: bsLit (nodeProgram nodeSettings)
      In the expression: ("node", bsLit (nodeProgram nodeSettings))
~~~

**Comment by sighingnow** [comment]
Close as fixed.
